name: ci

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        description: Deploy to Dev

env:
  # IMAGE_REGISTRY: docker.artifactory.banno-tools.com
  # IMAGE_NAME: odi-processor-service
  # PRODUCT: jh-digitalcore  
  IMAGE_REGISTRY: ballin24x7
  IMAGE_NAME: odi-gitops2
  PRODUCT: labs  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # - uses: actions/checkout@v3
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v2
      #   with:
      #     dotnet-version: 6.0.x

      - name: Setting variables for Docker Image Tag
        run: |
          echo "DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
          echo "GIT_HASH=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Display Github Runner Agent Environment variables
        run: |
          env | sort

      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - 
      #   name: Generate database files
      #   run: dotnet run --project ${{env.CONFIG_PROJECT_FILE}}  -- src/out           

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          #tags: ballin24x7/odi-gitops2:latest
          # tags: |
          #   ${{ env.IMAGE_REGISTRY }}/${{ env.PRODUCT }}/${{env.IMAGE_NAME}}:latest
          #   ${{ env.IMAGE_REGISTRY }}/${{ env.PRODUCT }}/${{env.IMAGE_NAME}}:${{ env.DATE }}${{ github.RUN_NUMBER }}
          #   ${{ env.IMAGE_REGISTRY }}/${{ env.PRODUCT }}/${{env.IMAGE_NAME}}:${{ env.GIT_HASH }}
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{env.IMAGE_NAME}}:latest
            ${{ env.IMAGE_REGISTRY }}/${{env.IMAGE_NAME}}:${{ env.DATE }}${{ github.RUN_NUMBER }}
            ${{ env.IMAGE_REGISTRY }}/${{env.IMAGE_NAME}}:${{ env.GIT_HASH }}
